name: Auto Labeler

on:
  pull_request:
    types: [opened, edited, synchronize]
  issues:
    types: [opened, edited]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9
        with:
          configuration-path: .github/labeler.yml
